# SpectreOS VM host — QEMU/KVM install target for testing.
#
# Usage during VM setup:
#   1. Boot NixOS installer ISO inside a VM
#   2. Partition and mount disks
#   3. Run nixos-generate-config --root /mnt
#      (generates /mnt/etc/nixos/hardware-configuration.nix with correct UUIDs)
#   4. Copy this repo to /mnt/etc/nixos/ (or clone it there)
#   5. Point /mnt/etc/nixos/configuration.nix at this file and run nixos-install
#
# hardware-configuration.nix is NOT committed here — it is generated per VM
# instance because disk UUIDs differ. The installer injects it (same pattern
# as hosts/px13/).

{ config, pkgs, lib, ... }:

{
  imports = [
    # Generated by nixos-generate-config during VM install — not committed.
    ./hardware-configuration.nix

    # SpectreOS base
    ../../configuration.nix

    # User account — replace with installer-generated file on real installs.
    ./user.nix
  ];

  networking.hostName = "spectreos-vm";

  # virtio_gpu provides KMS/DRM support for the QEMU virtio display device.
  # Required for niri — it skips software renderers and needs a real KMS node.
  boot.initrd.availableKernelModules = [ "virtio_gpu" ];

  # QEMU guest agent — enables clean shutdown, file transfer, and guest info
  # from the hypervisor. No-op outside a QEMU/KVM guest.
  services.qemuGuest.enable = true;

  # SSH for easier VM access (connect from host instead of using the console).
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = true;
  };
}
