#!/usr/bin/env bash
# SpectreOS VM installer
# Run from a NixOS live ISO as root: sudo bash install.sh
#
# What this does:
#   1. Partitions and formats the target disk (EFI + root)
#   2. Mounts, runs nixos-generate-config to capture hardware UUIDs
#   3. Clones the SpectreOS repo and places it under /mnt/etc/nixos/
#   4. Prompts for a username and password, writes hosts/vm/user.nix
#   5. Writes a minimal entry-point configuration.nix
#   6. Runs nixos-install

set -euo pipefail

REPO_URL="https://github.com/MilesChatterji/SpectreOS-Main"
SPECTREOS_DIR="/mnt/etc/nixos/spectreos"

info()  { echo "==> $*"; }
error() { echo "error: $*" >&2; exit 1; }

# --- preflight ---
[[ $EUID -eq 0 ]] || error "Run as root (sudo bash install.sh)"
command -v parted &>/dev/null || error "parted not found"

# Hash a password using openssl, fetching it via nix-shell if not in PATH.
hash_password() {
  if command -v openssl &>/dev/null; then
    openssl passwd -6 -stdin <<< "$1"
  else
    info "openssl not in PATH — fetching via nix-shell (one-time download)..."
    nix-shell -p openssl --run 'openssl passwd -6 -stdin' <<< "$1"
  fi
}

# --- disk selection ---
echo ""
echo "Available disks:"
lsblk -d -o NAME,SIZE,MODEL | grep -v loop
echo ""
read -rp "Target disk [/dev/vda]: " DISK
DISK="${DISK:-/dev/vda}"
[[ -b "$DISK" ]] || error "Disk $DISK not found"

echo ""
echo "WARNING: All data on $DISK will be erased."
read -rp "Type 'yes' to continue: " CONFIRM
[[ "$CONFIRM" == "yes" ]] || error "Aborted."

# --- user details ---
echo ""
read -rp "Username: " USERNAME
[[ -n "$USERNAME" ]] || error "Username cannot be empty"
read -rp "Full name: " FULLNAME
while true; do
  read -rsp "Password: " PASSWORD; echo ""
  read -rsp "Confirm password: " PASSWORD2; echo ""
  [[ "$PASSWORD" == "$PASSWORD2" ]] && break
  echo "Passwords do not match — try again."
done

# --- partition ---
info "Partitioning $DISK..."
parted -s "$DISK" mklabel gpt
parted -s "$DISK" mkpart ESP fat32 1MiB 512MiB
parted -s "$DISK" set 1 esp on
parted -s "$DISK" mkpart primary ext4 512MiB 100%

# Give the kernel time to see the new partition table
sleep 2

# Derive partition device names (handles /dev/vda → vda1, /dev/nvme0n1 → nvme0n1p1)
if [[ "$DISK" =~ (nvme|mmcblk) ]]; then
  PART1="${DISK}p1"
  PART2="${DISK}p2"
else
  PART1="${DISK}1"
  PART2="${DISK}2"
fi

# --- format ---
info "Formatting partitions..."
mkfs.fat -F 32 -n BOOT "$PART1"
mkfs.ext4 -L nixos -F "$PART2"

# --- mount ---
info "Mounting..."
mount /dev/disk/by-label/nixos /mnt
mkdir -p /mnt/boot
mount /dev/disk/by-label/BOOT /mnt/boot

# --- hardware config ---
info "Generating hardware configuration..."
nixos-generate-config --root /mnt

# --- clone SpectreOS ---
info "Fetching SpectreOS configuration..."
if ! command -v git &>/dev/null; then
  info "git not found — installing via nix-env..."
  nix-env -iA nixpkgs.git
fi
git clone "$REPO_URL" "$SPECTREOS_DIR"

# --- place hardware config ---
# nixos-generate-config writes to /mnt/etc/nixos/; hosts/vm/default.nix
# imports ./hardware-configuration.nix relative to its own directory.
cp /mnt/etc/nixos/hardware-configuration.nix \
   "$SPECTREOS_DIR/hosts/vm/hardware-configuration.nix"

# --- user.nix ---
info "Writing user configuration..."
HASHED_PASSWORD=$(hash_password "$PASSWORD")

cat > "$SPECTREOS_DIR/hosts/vm/user.nix" <<EOF
# Generated by SpectreOS VM installer — do not edit directly.
{ pkgs, ... }:
{
  users.users.$USERNAME = {
    isNormalUser = true;
    description = "$FULLNAME";
    hashedPassword = "$HASHED_PASSWORD";
    extraGroups = [
      "networkmanager"
      "wheel"
      "video"
      "render"
      "libvirtd"
    ];
    packages = [];
  };
}
EOF

# --- entry-point configuration.nix ---
# nixos-install looks for /mnt/etc/nixos/configuration.nix by default.
# We replace the generated one with a single-line import pointing at the
# SpectreOS VM host entry point.
cat > /mnt/etc/nixos/configuration.nix <<'NIXEOF'
# Generated by SpectreOS VM installer — do not edit directly.
# To customise the install, edit hosts/vm/ inside the spectreos directory.
{ ... }:
{ imports = [ ./spectreos/hosts/vm/default.nix ]; }
NIXEOF

# --- install ---
info "Installing SpectreOS (this will take a while)..."
nixos-install --no-root-passwd

echo ""
info "Done. SpectreOS is installed."
echo ""
echo "  Username : $USERNAME"
echo "  SSH      : ssh $USERNAME@<vm-ip>  (enabled, password auth on)"
echo ""
echo "Run 'reboot' to start SpectreOS."
