#!/usr/bin/env bash
# SpectreOS VM installer
# Run from a NixOS live ISO as root: sudo bash install.sh
#
# What this does:
#   1. Partitions and formats the target disk (EFI + root)
#   2. Mounts, runs nixos-generate-config to capture hardware UUIDs
#   3. Clones the SpectreOS repo and places it under /mnt/etc/nixos/
#   4. Prompts for a username and password, writes hosts/vm/user.nix
#   5. Writes a minimal entry-point configuration.nix
#   6. Runs nixos-install

set -euo pipefail

REPO_URL="https://github.com/MilesChatterji/SpectreOS-Main"
SPECTREOS_DIR="/mnt/etc/nixos/spectreos"

info()  { echo "==> $*"; }
error() { echo "error: $*" >&2; exit 1; }

# --- preflight ---
[[ $EUID -eq 0 ]] || error "Run as root (sudo bash install.sh)"
command -v parted &>/dev/null || error "parted not found"

# Hash a password using openssl, fetching it via nix-shell if not in PATH.
# Status messages go to stderr so they are not captured by $(...).
hash_password() {
  if command -v openssl &>/dev/null; then
    openssl passwd -6 -stdin <<< "$1"
  else
    echo "==> openssl not in PATH — fetching via nix-shell (one-time download)..." >&2
    nix-shell -p openssl --run 'openssl passwd -6 -stdin' <<< "$1"
  fi
}

# --- disk selection ---
echo ""
echo "Available disks:"
lsblk -d -o NAME,SIZE,MODEL | grep -v loop
echo ""
read -rp "Target disk [/dev/vda]: " DISK
DISK="${DISK:-/dev/vda}"
[[ -b "$DISK" ]] || error "Disk $DISK not found"

echo ""
echo "WARNING: All data on $DISK will be erased."
read -rp "Type 'yes' to continue: " CONFIRM
[[ "$CONFIRM" == "yes" ]] || error "Aborted."

# --- user details ---
echo ""
read -rp "Username: " USERNAME
[[ -n "$USERNAME" ]] || error "Username cannot be empty"
read -rp "Full name: " FULLNAME
while true; do
  read -rsp "Password: " PASSWORD; echo ""
  read -rsp "Confirm password: " PASSWORD2; echo ""
  [[ "$PASSWORD" == "$PASSWORD2" ]] && break
  echo "Passwords do not match — try again."
done

# --- partition ---
info "Partitioning $DISK..."
parted -s "$DISK" mklabel gpt
parted -s "$DISK" mkpart ESP fat32 1MiB 512MiB
parted -s "$DISK" set 1 esp on
parted -s "$DISK" mkpart primary ext4 512MiB 100%

# Give the kernel time to see the new partition table
sleep 2

# Derive partition device names (handles /dev/vda → vda1, /dev/nvme0n1 → nvme0n1p1)
if [[ "$DISK" =~ (nvme|mmcblk) ]]; then
  PART1="${DISK}p1"
  PART2="${DISK}p2"
else
  PART1="${DISK}1"
  PART2="${DISK}2"
fi

# --- format ---
info "Formatting partitions..."
mkfs.fat -F 32 -n BOOT "$PART1"
mkfs.ext4 -L nixos -F "$PART2"

# --- mount ---
info "Mounting..."
# Wait for udev to create /dev/disk/by-label/ symlinks after mkfs
udevadm settle
mount /dev/disk/by-label/nixos /mnt
mkdir -p /mnt/boot
mount /dev/disk/by-label/BOOT /mnt/boot

# --- hardware config ---
info "Generating hardware configuration..."
nixos-generate-config --root /mnt

# --- clone SpectreOS ---
info "Fetching SpectreOS configuration..."
if ! command -v git &>/dev/null; then
  info "git not found — installing via nix-env..."
  nix-env -iA nixpkgs.git
fi
git clone "$REPO_URL" "$SPECTREOS_DIR"

# --- place hardware config ---
# nixos-generate-config writes to /mnt/etc/nixos/; hosts/vm/default.nix
# imports ./hardware-configuration.nix relative to its own directory.
cp /mnt/etc/nixos/hardware-configuration.nix \
   "$SPECTREOS_DIR/hosts/vm/hardware-configuration.nix"

# --- user.nix ---
info "Writing user configuration..."
HASHED_PASSWORD=$(hash_password "$PASSWORD")

cat > "$SPECTREOS_DIR/hosts/vm/user.nix" <<EOF
# Generated by SpectreOS VM installer — do not edit directly.
{ pkgs, ... }:
{
  users.users.$USERNAME = {
    isNormalUser = true;
    description = "$FULLNAME";
    hashedPassword = "$HASHED_PASSWORD";
    extraGroups = [
      "networkmanager"
      "wheel"
      "video"
      "render"
      "libvirtd"
    ];
    packages = [];
  };
}
EOF

# --- entry-point configuration.nix ---
# nixos-install looks for /mnt/etc/nixos/configuration.nix by default.
# We replace the generated one with a single-line import pointing at the
# SpectreOS VM host entry point.
cat > /mnt/etc/nixos/configuration.nix <<'NIXEOF'
# Generated by SpectreOS VM installer — do not edit directly.
# To customise the install, edit hosts/vm/ inside the spectreos directory.
{ ... }:
{ imports = [ ./spectreos/hosts/vm/default.nix ]; }
NIXEOF

# --- install ---
info "Installing SpectreOS (this will take a while)..."
nixos-install --no-root-passwd

# --- default configs and branding ---
info "Installing default configurations..."
nixos-enter --root /mnt -- mkdir -p \
  /home/$USERNAME/.config/niri/niri-animation-collection-main/animations \
  /home/$USERNAME/.config/noctalia \
  /home/$USERNAME/.config/home-manager \
  /home/$USERNAME/Pictures/SpectreOS \
  /home/$USERNAME/.local/share/spectreos \
  /home/$USERNAME/.local/share/fonts \
  /home/$USERNAME/.local/state/nix/profiles

nixos-enter --root /mnt -- mkdir -p /nix/var/nix/profiles/per-user/$USERNAME
nixos-enter --root /mnt -- chown $USERNAME:users /nix/var/nix/profiles/per-user/$USERNAME

nixos-enter --root /mnt -- cp /etc/nixos/spectreos/defaults/niri/config.kdl        /home/$USERNAME/.config/niri/config.kdl
nixos-enter --root /mnt -- cp /etc/nixos/spectreos/defaults/niri/noctalia.kdl       /home/$USERNAME/.config/niri/noctalia.kdl
nixos-enter --root /mnt -- cp /etc/nixos/spectreos/defaults/niri/niri-animation-collection-main/animations/crt_degauss.kdl \
  /home/$USERNAME/.config/niri/niri-animation-collection-main/animations/crt_degauss.kdl
nixos-enter --root /mnt -- cp /etc/nixos/spectreos/defaults/noctalia/settings.json /home/$USERNAME/.config/noctalia/settings.json
nixos-enter --root /mnt -- cp /etc/nixos/spectreos/assets/branding/SpectreOSWall.png /home/$USERNAME/Pictures/SpectreOS/SpectreOSWall.png
nixos-enter --root /mnt -- cp /etc/nixos/spectreos/assets/branding/Spectreicon.png   /home/$USERNAME/.local/share/spectreos/Spectreicon.png
nixos-enter --root /mnt -- cp /etc/nixos/spectreos/assets/fonts/ndot-47-inspired-by-nothing.ttf \
  /home/$USERNAME/.local/share/fonts/ndot-47-inspired-by-nothing.ttf
nixos-enter --root /mnt -- fc-cache /home/$USERNAME/.local/share/fonts

# Patch noctalia config with the actual branding paths for this user.
cat > /tmp/patch_noctalia.py << PYEOF
import json
cfg_path = '/mnt/home/$USERNAME/.config/noctalia/settings.json'
with open(cfg_path) as f:
    cfg = json.load(f)
cfg['wallpaper']['directory'] = '/home/$USERNAME/Pictures/SpectreOS'
cfg['wallpaper']['useSolidColor'] = False
for w in cfg.get('bar', {}).get('widgets', {}).get('left', []):
    if w.get('id') == 'ControlCenter':
        w['customIconPath'] = '/home/$USERNAME/.local/share/spectreos/Spectreicon.png'
with open(cfg_path, 'w') as f:
    json.dump(cfg, f, indent=4)
PYEOF
nix-shell -p python3 --run "python3 /tmp/patch_noctalia.py"

# --- fix ownership before home-manager runs ---
info "Setting ownership on home directory..."
nixos-enter --root /mnt -- chown $USERNAME:users /home/$USERNAME
nixos-enter --root /mnt -- chown -R $USERNAME:users \
  /home/$USERNAME/.config \
  /home/$USERNAME/Pictures \
  /home/$USERNAME/.local

# --- home-manager ---
info "Writing home-manager configuration..."
# Copy the template and substitute the username in-place.
nixos-enter --root /mnt -- cp \
  /etc/nixos/spectreos/defaults/hm-entry.nix \
  /home/$USERNAME/.config/home-manager/home.nix
nixos-enter --root /mnt -- sed -i \
  "s/__USERNAME__/$USERNAME/g" \
  /home/$USERNAME/.config/home-manager/home.nix

# home-manager switch cannot run inside nixos-enter (no systemd --user session).
# Instead, drop a flag file and a setup script that niri will launch in ghostty
# on first login (via spawn-sh-at-startup in config.kdl).
info "Writing first-boot home-manager setup script..."
cp /mnt/etc/nixos/spectreos/defaults/hm-setup.sh \
   /mnt/home/$USERNAME/.local/share/spectreos/hm-setup.sh
chmod +x /mnt/home/$USERNAME/.local/share/spectreos/hm-setup.sh

# Flag file — presence triggers the ghostty launch on first niri login.
touch /mnt/home/$USERNAME/.hm-pending

# Fix ownership of files written after the initial chown (home.nix, setup script, flag).
nixos-enter --root /mnt -- chown -R $USERNAME:users /home/$USERNAME/.config
nixos-enter --root /mnt -- chown $USERNAME:users \
  /home/$USERNAME/.local/share/spectreos/hm-setup.sh \
  /home/$USERNAME/.hm-pending

echo ""
info "Done. SpectreOS is installed."
echo ""
echo "  Username : $USERNAME"
echo "  SSH      : ssh $USERNAME@<vm-ip>  (enabled, password auth on)"
echo ""
echo "Rebooting in 5 seconds... (Ctrl+C to cancel)"
for i in 5 4 3 2 1; do
    printf "  %s...\n" "$i"
    sleep 1
done
reboot
