# VM test user — generated by the installer on a real install.
# Replace this file's contents with installer output for production builds.

{ pkgs, ... }:

{
  users.users.miles = {
    isNormalUser = true;
    description = "Miles Chatterji";
    extraGroups = [
      "networkmanager"
      "wheel"
      "video"
      "render"
      "libvirtd"
    ];
    packages = with pkgs; [];
  };
}
