# Generated by SpectreOS VM installer — do not edit directly.
# To customise, edit defaults/home.nix in the spectreos repo.
# Extra packages managed by the SpectreOS Package Manager are in
# ~/.config/spectreos/extra-packages.nix and auto-imported if present.
{ lib, ... }:
let
  extraPkgs = /home/__USERNAME__/.config/spectreos/extra-packages.nix;
in
{
  imports =
    [ /etc/nixos/spectreos/defaults/home.nix ]
    ++ lib.optional (builtins.pathExists extraPkgs) extraPkgs;
  home.username = "__USERNAME__";
  home.homeDirectory = "/home/__USERNAME__";
}
