# Generated by SpectreOS VM installer — do not edit directly.
# To customise, edit defaults/home.nix in the spectreos repo.
{ ... }:
{
  imports = [ /etc/nixos/spectreos/defaults/home.nix ];
  home.username = "__USERNAME__";
  home.homeDirectory = "/home/__USERNAME__";
}
